### ISSUE TITLE
table doesn't have borders

### ISSUE THREAD

**Issue by emilypark0418** [kevincobain2000/json-to-html-table#1]
hi, i installed the npm package but seems like table borderlines are not showing.
Anyway I can fix this?

**Comment by kevincobain2000** [comment]
Can you post a screenshot please

**Comment by emilypark0418** [comment]
Sure. As you can see, the table doesn't have any boundaries.

[image: Screen Shot 2022-07-03 at 6.09.28 PM.png]

**Comment by kevincobain2000** [comment]
I can't see the image.

**Comment by kevincobain2000** [comment]
And it could be most likely that you have some CSS property on the table that is overriding (or missing) in the default css.

You can try passing the class like below:

```
<JSONToHTMLTable data={data} tableClassName="table table-sm table-bordered"/>
                                                                                                                   ↑↑↑↑↑
```

depending on what css framework/library you are using, `table-bordered` this'd be different.

**Comment by emilypark0418** [comment]
Hmm okay I'll try take a look based on your advice, and reach out again if
it still doesn't resolve my issue!
Thanks again!
